package com.mediguru.app.util

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import com.itextpdf.io.image.ImageDataFactory
import com.itextpdf.kernel.colors.ColorConstants
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Image
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.property.TextAlignment
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

object PdfGenerator {

    fun generateMedicalReport(
        context: Context,
        transcription: String,
        doctorResponse: String,
        imageUri: Uri?
    ): File? {
        return try {
            val fileName = "MediGuru_Report_${System.currentTimeMillis()}.pdf"
            val file = File(context.getExternalFilesDir(null), fileName)
            val writer = PdfWriter(FileOutputStream(file))
            val pdf = PdfDocument(writer)
            val document = Document(pdf)

            // Header
            document.add(
                Paragraph("MediGuru AI - Clinical Report")
                    .setFontSize(24f)
                    .setBold()
                    .setFontColor(ColorConstants.BLUE)
                    .setTextAlignment(TextAlignment.CENTER)
            )

            val sdf = SimpleDateFormat("MMM dd, yyyy HH:mm", Locale.getDefault())
            document.add(
                Paragraph("Date: ${sdf.format(Date())}")
                    .setTextAlignment(TextAlignment.RIGHT)
                    .setFontSize(10f)
            )

            document.add(Paragraph("\n"))

            // Patient Symptoms
            document.add(Paragraph("Patient Symptoms:").setBold().setFontSize(14f))
            document.add(Paragraph(if (transcription.isBlank()) "None provided (image-only analysis)" else transcription))
            document.add(Paragraph("\n"))

            // AI Board Consensus
            document.add(Paragraph("Medical Board Consensus:").setBold().setFontSize(14f).setFontColor(ColorConstants.DARK_GRAY))
            document.add(Paragraph(doctorResponse).setItalic())
            document.add(Paragraph("\n"))

            // Medical Image if exists
            imageUri?.let { uri ->
                try {
                    val inputStream = context.contentResolver.openInputStream(uri)
                    val bitmap = BitmapFactory.decodeStream(inputStream)
                    val stream = ByteArrayOutputStream()
                    bitmap.compress(Bitmap.CompressFormat.JPEG, 70, stream)
                    val imageData = ImageDataFactory.create(stream.toByteArray())
                    val image = Image(imageData).setMaxWidth(400f).setHorizontalAlignment(com.itextpdf.layout.property.HorizontalAlignment.CENTER)
                    document.add(Paragraph("Attached Medical Scan:").setBold())
                    document.add(image)
                } catch (e: Exception) {
                    document.add(Paragraph("[Image processing failed]"))
                }
            }

            // Footer
            document.add(Paragraph("\n\n\n"))
            document.add(
                Paragraph("Disclaimer: This report is generated by an AI Multi-Agent Board and is for informational purposes only. Please consult a licensed human physician before taking any medical action.")
                    .setFontSize(8f)
                    .setFontColor(ColorConstants.RED)
                    .setTextAlignment(TextAlignment.CENTER)
            )

            document.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }
}
